package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/jimbottle/would-you-kindly/internal/tui"
)

// runHelp handles `wyk help`. Defaults to a pointer at the in-TUI
// overlay (`?`). Two opt-in flags emit machine-readable references
// for downstream consumers (docs site, agent prompts):
//
//	--markdown        TUI keymap reference, sourced from
//	                  internal/tui.DocsKeymap.
//	--cli-markdown    Per-subcommand flag surface, walked from the
//	                  cliSubcommandDocs table (cmd/wyk/clidocs.go).
//
// Both outputs are pinned to disk in docs/generated/ via the
// docs-snapshot Makefile target so the docs site can read them
// without a Go toolchain.
//
// Exit codes:
//
//	0  reference printed (or pointer-to-TUI message printed)
//	64 usage error
func runHelp(args []string) int {
	fs := flag.NewFlagSet("help", flag.ContinueOnError)
	asMarkdown := fs.Bool("markdown", false, "emit a markdown keymap reference (single source of truth: internal/tui.DocsKeymap)")
	asCLIMarkdown := fs.Bool("cli-markdown", false, "emit a markdown CLI-flag reference for every subcommand (single source of truth: cliSubcommandDocs)")
	fs.SetOutput(os.Stderr)
	if err := fs.Parse(args); err != nil {
		return 64
	}
	if fs.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "usage: wyk help [--markdown] [--cli-markdown]")
		return 64
	}
	if *asMarkdown && *asCLIMarkdown {
		fmt.Fprintln(os.Stderr, "wyk help: --markdown and --cli-markdown are mutually exclusive")
		return 64
	}
	if *asMarkdown {
		fmt.Print(tui.KeymapMarkdown())
		return 0
	}
	if *asCLIMarkdown {
		emitCLIMarkdown(os.Stdout, cliSubcommandDocs)
		return 0
	}
	// No flag: be useful but minimal. Point at the in-TUI overlay
	// for full context (binding chains, mouse hints, status legend).
	fmt.Println("wyk help: launch wyk and press `?` for the full key reference.")
	fmt.Println("  --markdown      emit the generated TUI keymap reference")
	fmt.Println("  --cli-markdown  emit the generated CLI flag reference")
	return 0
}

// emitCLIMarkdown writes a markdown page documenting every
// subcommand in the supplied table. The output shape is stable
// across patch releases — the would-you-kindly.raylytics.io docs
// agent reads it verbatim. A toplevel H1 plus per-subcommand H2
// sections, each with a one-line summary, a fenced usage line,
// and a flags table (Name / Default / Description) — or "no
// flags" when the subcommand takes none.
func emitCLIMarkdown(w io.Writer, docs []cliSubcommandDoc) {
	fmt.Fprintln(w, "# wyk CLI reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by `wyk help --cli-markdown` — do not edit by hand.")
	fmt.Fprintln(w, "Source: `cmd/wyk/clidocs.go`.")
	fmt.Fprintln(w)
	for _, d := range docs {
		fmt.Fprintf(w, "## `wyk %s`\n\n", d.Name)
		fmt.Fprintln(w, d.Summary)
		fmt.Fprintln(w)
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w, d.Usage)
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w)
		if len(d.Flags) == 0 {
			fmt.Fprintln(w, "_no flags_")
			fmt.Fprintln(w)
			continue
		}
		fmt.Fprintln(w, "| Flag | Default | Description |")
		fmt.Fprintln(w, "| --- | --- | --- |")
		for _, f := range d.Flags {
			def := f.Default
			if def == "" {
				def = "_(empty)_"
			}
			// Pipe characters in description would break the table;
			// escape them. Backticks pass through fine.
			desc := strings.ReplaceAll(f.Description, "|", `\|`)
			fmt.Fprintf(w, "| `%s` | `%s` | %s |\n", f.Name, def, desc)
		}
		fmt.Fprintln(w)
	}
}
